// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://quzpssxbqwycpctlmsyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1enBzc3hicXd5Y3BjdGxtc3l2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNzY4MTYsImV4cCI6MjA2Njk1MjgxNn0.7Fvx67KjmpJgZlHEqI--BQKA3ETpLCXFRlOMUINgFu0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});